version: "3"
services:
  db:
      image: mcr.microsoft.com/mssql/server
      environment:
          SA_PASSWORD: P@55w0rd
          ACCEPT_EULA: Y
      ports:
        - 1433:1433
      volumes: 
        - mssql-db:/var/opt/mssql

volumes: 
  mssql-db:
    driver: local